# Generated by Django 5.0.6 on 2024-07-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_file_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
