# Generated by Django 5.0.6 on 2024-07-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_file_file_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_tags',
        ),
        migrations.AddField(
            model_name='file',
            name='file_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
