# Generated by Django 5.0.6 on 2024-07-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_dialogue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='techie',
            name='is_dark',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.file'),
        ),
        migrations.AddField(
            model_name='techie',
            name='user_plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techie',
            name='avatar',
            field=models.ImageField(default='logo.svg', upload_to=''),
        ),
    ]
