# Generated by Django 5.0.6 on 2024-07-13 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_tag_remove_techie_is_dark_dialogue_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
