# Generated by Django 5.0.6 on 2024-07-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_file_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techie',
            name='user_plan',
            field=models.CharField(default='basic', max_length=100, null=True),
        ),
    ]
