# Generated by Django 5.0.6 on 2024-07-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_techie_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techie',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
